$schema: https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - name: Update post from Instagram
    image: node:22
    environment:
      ACCOUNT_ID:
        from_secret: account_id
      AUTHORIZATION_KEY:
        from_secret: authorization_key
    when:
      event: cron
      cron: update-post
    commands:
      - printf "ACCOUNT_ID=${ACCOUNT_ID} \nAUTHORIZATION_KEY=${AUTHORIZATION_KEY}\n" > ./scripts/.env
      - node ./scripts/get-instagram-post.js
